// THIS IS AN AUTOMATICALLY GENERATED FILE.
// DO NOT MODIFY BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#ifndef ZCM_EMBEDDED
#include <stdio.h>
#endif
#include "otp_t.h"

static int __otp_t_hash_computed = 0;
static uint64_t __otp_t_hash;

uint64_t __otp_t_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __otp_t_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__otp_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x2495cbc60b201457LL
         + __int8_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __otp_t_get_hash(void)
{
    if (!__otp_t_hash_computed) {
        __otp_t_hash = (int64_t)__otp_t_hash_recursive(NULL);
        __otp_t_hash_computed = 1;
    }

    return __otp_t_hash;
}

int __otp_t_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const otp_t* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].state), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].roll), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].pitch), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].yaw), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].acceleration), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].position), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].angular_rate), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int otp_t_encode(void* buf, uint32_t offset, uint32_t maxlen, const otp_t* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __otp_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __otp_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __otp_t_encoded_array_size(const otp_t* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __int8_t_encoded_array_size(&(p[element].state), 1);

        size += __float_encoded_array_size(&(p[element].roll), 1);

        size += __float_encoded_array_size(&(p[element].pitch), 1);

        size += __float_encoded_array_size(&(p[element].yaw), 1);

        size += __float_encoded_array_size(&(p[element].acceleration), 1);

        size += __float_encoded_array_size(&(p[element].position), 1);

        size += __float_encoded_array_size(&(p[element].angular_rate), 1);

    }
    return size;
}

uint32_t otp_t_encoded_size(const otp_t* p)
{
    return 8 + __otp_t_encoded_array_size(p, 1);
}

int __otp_t_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, otp_t* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].state), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].roll), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].pitch), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].yaw), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].acceleration), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].position), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].angular_rate), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __otp_t_decode_array_cleanup(otp_t* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __int8_t_decode_array_cleanup(&(p[element].state), 1);

        __float_decode_array_cleanup(&(p[element].roll), 1);

        __float_decode_array_cleanup(&(p[element].pitch), 1);

        __float_decode_array_cleanup(&(p[element].yaw), 1);

        __float_decode_array_cleanup(&(p[element].acceleration), 1);

        __float_decode_array_cleanup(&(p[element].position), 1);

        __float_decode_array_cleanup(&(p[element].angular_rate), 1);

    }
    return 0;
}

int otp_t_decode(const void* buf, uint32_t offset, uint32_t maxlen, otp_t* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __otp_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __otp_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int otp_t_decode_cleanup(otp_t* p)
{
    return __otp_t_decode_array_cleanup(p, 1);
}

uint32_t __otp_t_clone_array(const otp_t* p, otp_t* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __int8_t_clone_array(&(p[element].state), &(q[element].state), 1);

        n += __float_clone_array(&(p[element].roll), &(q[element].roll), 1);

        n += __float_clone_array(&(p[element].pitch), &(q[element].pitch), 1);

        n += __float_clone_array(&(p[element].yaw), &(q[element].yaw), 1);

        n += __float_clone_array(&(p[element].acceleration), &(q[element].acceleration), 1);

        n += __float_clone_array(&(p[element].position), &(q[element].position), 1);

        n += __float_clone_array(&(p[element].angular_rate), &(q[element].angular_rate), 1);

    }
    return n;
}

otp_t* otp_t_copy(const otp_t* p)
{
    otp_t* q = (otp_t*) malloc(sizeof(otp_t));
    __otp_t_clone_array(p, q, 1);
    return q;
}

void otp_t_destroy(otp_t* p)
{
    __otp_t_decode_array_cleanup(p, 1);
    free(p);
}

int otp_t_publish(zcm_t* zcm, const char* channel, const otp_t* p)
{
      uint32_t max_data_size = otp_t_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = otp_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _otp_t_subscription_t {
    otp_t_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void otp_t_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    otp_t p;
    memset(&p, 0, sizeof(otp_t));
    status = otp_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr, "error %d decoding otp_t!!!\n", status);
        #endif
        return;
    }

    otp_t_subscription_t* h = (otp_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    otp_t_decode_cleanup (&p);
}

otp_t_subscription_t* otp_t_subscribe (zcm_t* zcm,
                    const char* channel,
                    otp_t_handler_t f, void* userdata)
{
    otp_t_subscription_t* n = (otp_t_subscription_t*)
                       malloc(sizeof(otp_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              otp_t_handler_stub, n);
    if (n->z_sub == NULL) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr,"couldn't reg otp_t ZCM handler!\n");
        #endif
        free (n);
        return NULL;
    }
    return n;
}

int otp_t_unsubscribe(zcm_t* zcm, otp_t_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        #ifndef ZCM_EMBEDDED
        fprintf(stderr,
           "couldn't unsubscribe otp_t_handler %p!\n", hid);
        #endif
        return -1;
    }
    free (hid);
    return 0;
}

