# FSM Data
CURRENT_STATE = "acceleration"

# Battery Pack Data
BATTERY_CURRENT_TEMP = 0
BATTERY_MAXIMUM_TEMP = 100
BATTERY_AVG_TEMP = 0

# Inductive Proximity Sensor Data
PROXIMITY_INPUT1 = 2
PROXIMITY_LED1 = 13
PROXIMITY_SENSOR_STATE1 = "high"
PROXIMITY_INPUT2 = 2
PROXIMITY_LED2 = 13
PROXIMITY_SENSOR_STATE2 = "high"
PROXIMITY_INPUT3 = 2
PROXIMITY_LED3 = 13
PROXIMITY_SENSOR_STATE3 = "high"
PROXIMITY_INPUT4 = 2
PROXIMITY_LED4 = 13
PROXIMITY_SENSOR_STATE4 = "high"

# Vibration Sensor Data
BUTTON_PIN = 2
BUZZER = 3
BUTTON_STATE = 0

# Inertial Measurement Unit Data
CURRENT_VELOCITY = 2
ACCELERATION = 3
PITCH = [90, -132, 54, 2]
YAW = [129, 0, -83, 324]
ROLL = [-12, 55, 39, 360]

# Pressure Sensor Data
CURRENT_TEMPERATURE = 40
ALTITUDE = 50
PRESSURE = 20

# Long Distance Range Finder Data
DISTANCE = 30
